etcd:
  image: quay.io/coreos/etcd
  restart: always
  command: >
    -advertise-client-urls="http://0.0.0.0:2379,http://0.0.0.0:4001"
    -listen-client-urls="http://0.0.0.0:2379,http://0.0.0.0:4001"

psql0:
  image: os/govenror:latest
  restart: always
  environment:
    GOVERNOR_ETCD_HOST: etcd:2379
    GOVERNOR_POSTGRESQL_NAME: postgresql1
    GOVERNOR_POSTGRESQL_DATA_DIR: /data/postgres
  links:
    - etcd
  volumes:
    - "./pg_hba.conf:/governor/pg_hba.conf"

psql1:
  image: os/govenror:latest
  restart: always
  environment:
    GOVERNOR_ETCD_HOST: etcd:2379
    GOVERNOR_POSTGRESQL_NAME: postgresql2
    GOVERNOR_POSTGRESQL_DATA_DIR: /data/postgres
  links:
    - etcd
  volumes:
    - "./pg_hba.conf:/governor/pg_hba.conf"
